"""empty message

Revision ID: 47ae28c976fd
Revises: 9be0bdf23496
Create Date: 2021-04-15 13:13:54.937816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ae28c976fd'
down_revision = '9be0bdf23496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('winemaker_facebook_link_key', 'winemaker', type_='unique')
    op.drop_column('winemaker', 'availability')
    op.drop_constraint('winery_facebook_link_key', 'winery', type_='unique')
    op.drop_constraint('winery_phone_key', 'winery', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('winery_phone_key', 'winery', ['phone'])
    op.create_unique_constraint('winery_facebook_link_key', 'winery', ['facebook_link'])
    op.add_column('winemaker', sa.Column('availability', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.create_unique_constraint('winemaker_facebook_link_key', 'winemaker', ['facebook_link'])
    # ### end Alembic commands ###
