"""empty message

Revision ID: 4be81656bb81
Revises: 0f0b7dbaa161
Create Date: 2021-01-18 13:19:19.356662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4be81656bb81'
down_revision = '0f0b7dbaa161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('address', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'address')
    # ### end Alembic commands ###
