"""empty message

Revision ID: 7133170b6fe9
Revises: ae1b0476d48a
Create Date: 2021-04-16 22:06:35.172989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7133170b6fe9'
down_revision = 'ae1b0476d48a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('winery_facebook_link_key', 'winery', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('winery_facebook_link_key', 'winery', ['facebook_link'])
    # ### end Alembic commands ###
