"""empty message

Revision ID: 9be0bdf23496
Revises: 23ff4668b218
Create Date: 2021-01-22 12:59:05.874598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be0bdf23496'
down_revision = '23ff4668b218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('availability', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'availability')
    # ### end Alembic commands ###
