"""empty message

Revision ID: ae1b0476d48a
Revises: ca672ea49570
Create Date: 2021-04-16 21:49:53.260981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae1b0476d48a'
down_revision = 'ca672ea49570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'winery', ['facebook_link'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'winery', type_='unique')
    # ### end Alembic commands ###
